[package]
name = "alienfan-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }
zvariant = "5.15"

[lints]
workspace = true
