[package]
name = "alienfan-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "alienfan"
path = "src/main.rs"

[dependencies]
alienfan-core = { version = "0.1.0", path = "../alienfan-core" }
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["fmt", "ansi"] }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.27.0"
